CREATE TABLE VEHICLE_ROW (
    KEY_FIELD VARCHAR(30) NOT NULL PRIMARY KEY,
    CAPACITY NUMBER(20),
    STATE VARCHAR(20)
);

CREATE TABLE VEHICLE_VIN (
    ID NUMBER(30) NOT NULL PRIMARY KEY,
    VIN VARCHAR(30),
    ROW_KEY_FIELD VARCHAR(30)
);

ALTER TABLE VEHICLE_VIN ADD CONSTRAINT
VEH_VIN_VEH_ROW FOREIGN KEY (ROW_KEY_FIELD) REFERENCES
VEHICLE_ROW(KEY_FIELD)
